image_sharing/image_sharing/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls')),
    url('social-auth/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

image_sharing/images/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$', views.image_create, name='create'),
    url(r'^detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.image_detail, name='detail'),
    url(r'^like/$', views.image_like, name='like'),
    url(r'^$', views.image_list, name='list'),
]

image_sharing/images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.core.urlresolvers import reverse
from unidecode import unidecode

class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='images_created')
    title = models.CharField(max_length=200,verbose_name = "标题")
    slug = models.SlugField(max_length=200,blank=True,verbose_name = '连体标题')
    url = models.URLField(verbose_name = "URL")
    image = models.ImageField(upload_to = 'images/%Y/%m/%d',verbose_name = '图片')
    description = models.TextField(blank=True,verbose_name = '简介')
    created = models.DateField(auto_now_add=True, db_index=True,verbose_name = '创建时间')
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='images_liked',
                                        blank=True,
                                        verbose_name = '喜欢的用户列表')
                                        
    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])
                                        
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.title))
        super(Image, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.title
        
    class Meta:
        verbose_name = '图片'
        verbose_name_plural = verbose_name

image_sharing/images/forms.py
from django import forms
from .models import Image
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify

class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        widgets = {
            'url': forms.HiddenInput,
        }

    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('目前仅支持jpg和jpeg')
        return url
        
    def save(self, force_insert=False, force_update=False, commit=True):
        image = super(ImageCreateForm, self).save(commit=False)
        image_url = self.cleaned_data['url']
        image_name = '{}.{}'.format(slugify(image.title), image_url.rsplit('.', 1)[1].lower())
        # 下载指定的图像URL
        response = request.urlopen(image_url)
        image.image.save(image_name, ContentFile(response.read()), save=False)
        if commit:
            image.save()
        # 注意返回的是image对象，然后就可以image.save()就存在数据库了
        return image

image_sharing/images/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import ImageCreateForm
from django.shortcuts import get_object_or_404
from .models import Image
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from common.decorators import ajax_required
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

@login_required
def image_create(request):
    if request.method == 'POST':
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            # 数据合法
            cd = form.cleaned_data
            # 先下载在本地存好图片
            new_item = form.save(commit=False)
            # 绑定登入的user
            new_item.user = request.user
            # Image对象存储
            new_item.save()
            messages.success(request, '图片成功添加！')
            # 重定向到image对象的详细情况的url
            return redirect(new_item.get_absolute_url())
    else:
        # js工具发出GET方法，会传入参数，构造出form
        form = ImageCreateForm(data=request.GET)
    return render(request,
                  'images/image/create.html',
                  {'section': 'images',
                  'form': form})
                  
                  

def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    return render(request,
                 'images/image/detail.html',
                 {'section': 'images',
                 'image': image})


@ajax_required
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status':'ok'})
        except:
            pass
    return JsonResponse({'status':'not-ok'})

@login_required
def image_list(request):
    images = Image.objects.all()
    paginator = Paginator(images, 8)
    page = request.GET.get('page')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        # 如果不是整数，从第一页开始
        images = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            # s是ajax，越界，返回空页
            return HttpResponse('')
        # 非ajax，越界返回最后一页
        images = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request,
                     'images/image/list_ajax.html',
                     {'section': 'images', 'images': images})
    return render(request,
                  'images/image/list.html',
                  {'section': 'images', 'images': images})

image_sharing/images/templates/images/image/create.html
{% extends "base.html" %}

{% block title %}记录分享一张图片{% endblock %}

{% block content %}
<h1>记录分享一张图片</h1>
<img src="{{ request.GET.url }}" class="image-preview">
<form action="." method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="记录分享图片">
</form>
{% endblock %}

image_sharing/images/templates/images/image/detail.html
{% extends "base.html" %}

{% block title %}{{ image.title }}{% endblock %}

{% block content %}
<h1>{{ image.title }}</h1>

{% load thumbnail %}
{% thumbnail image.image "300" as im %}
    <a href="{{ image.image.url }}">
        <img src="{{ im.url }}" class="image-detail">
    </a>
{% endthumbnail %}

{% with total_likes=image.users_like.count  users_like=image.users_like.all%}
    <div class="image-info">
        <div>
            <span class="count">
                <span class="total">{{ total_likes }}</span>人喜欢
            </span>
            <a href="#" id=like data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
                {% if request.user not in users_like %}
                    喜欢
                {% else %}
                    不喜欢
                {% endif %}
            </a>
        </div>
        
        {{ image.description|linebreaks }}
    </div>
            
    <div class="image-likes">
        {% for user in image.users_like.all %}
            <div>
                {% if user.profile.photo.image %}
                    <img src="{{ user.profile.photo.url }}">
                {% endif %}
                <p>{{ user.first_name }}</p>
            </div>
        {% empty %}
            目前未有人喜欢
        {% endfor %}
    </div>
{% endwith %}
{% endblock %}


{% block domready %}
    $('#like').click(function(e){
        e.preventDefault();
        $.post('{% url "images:like" %}',
                {
                    id: $(this).data('id'),
                    action: $(this).data('action')
                },
                function(data){
                    if (data['status'] == 'ok'){
                        var previous_action = $('a.like').data('action');
                        // toggle data-action
                        $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
                        // toggle link text
                        $('a.like').text(previous_action == 'like' ? '不喜欢' : '喜欢');
                        // update total likes
                        var previous_likes = parseInt($('span.count .total').text());
                        $('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
                    }
                }
            );
    });
{% endblock %}

image_sharing/images/templates/images/image/list.html
{% extends "base.html" %}
{% block title %}记录的图片{% endblock %}

{% block content %}
    <h1>记录的图片</h1>
    <div id="image-list">
        {% include "images/image/list_ajax.html" %}
    </div>
{% endblock %}

{% block domready %}
    var page = 1;
    var empty_page = false;
    var block_request = false;
    $(window).scroll(function() {
        var margin = $(document).height() - $(window).height() - 200;
        if ($(window).scrollTop() > margin && empty_page == false &&
                block_request == false) {
                block_request = true;
                page += 1;
                $.get('?page=' + page, function(data) {
                    if(data == '') {
                        empty_page = true;
                    }
                    else {
                        block_request = false;
                        $('#image-list').append(data);
                    }
                });
        }
    });
{% endblock %}

image_sharing/images/templates/images/image/list_ajax.html
{% load thumbnail %}

{% for image in images %}
    <div class="image">
        <a href="{{ image.get_absolute_url }}">
            {% thumbnail image.image "300x300" crop="100%" as im %}
                <a href="{{ image.get_absolute_url }}">
                    <img src="{{ im.url }}">
                </a>
            {% endthumbnail %}
        </a>
        <div class="info">
            <a href="{{ image.get_absolute_url }}" class="title">
            {{ image.title }}
            </a>
        </div>
    </div>
{% endfor %}