image_sharing/account/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
     # register url
     url(r'^register/$', views.register, name='register'),

    # login / logout urls
    url(r'^login/$',
        'django.contrib.auth.views.login',
        name='login'),
    url(r'^logout/$',
        'django.contrib.auth.views.logout',
        name='logout'),
    url(r'^logout-then-login/$',
        'django.contrib.auth.views.logout_then_login',
        name='logout_then_login'),
    url(r'^$', views.dashboard, name='dashboard'),
    
    # change password urls
    url(r'^password-change/$',
        'django.contrib.auth.views.password_change',
        name='password_change'),
    url(r'^password-change/done/$',
        'django.contrib.auth.views.password_change_done',
        name='password_change_done'),
        
        
    # restore password urls
    url(r'^password-reset/$',
        'django.contrib.auth.views.password_reset',
        name='password_reset'),
    url(r'^password-reset/done/$',
        'django.contrib.auth.views.password_reset_done',
        name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        name='password_reset_confirm'),
    url(r'^password-reset/complete/$',
        'django.contrib.auth.views.password_reset_complete',
        name='password_reset_complete'),
        
    url(r'^edit/$', views.edit, name='edit'),
]

image_sharing/image_sharing/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls')),
    url('social-auth/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

image_sharing/images/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$', views.image_create, name='create'),
    url(r'^detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.image_detail, name='detail'),
    url(r'^like/$', views.image_like, name='like'),
    url(r'^$', views.image_list, name='list'),
]

image_sharing/account/models.py
from django.db import models
from django.conf import settings

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    date_of_birth = models.DateField(blank=True, null=True, verbose_name = "出生日期")
    photo = models.ImageField(upload_to='users/%Y/%m/%d', blank=True, verbose_name = "头像")
    
    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)
        
    class Meta:
        verbose_name = '简档'
        verbose_name_plural = verbose_name
        

image_sharing/account/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label='账户名')
    password = forms.CharField(widget=forms.PasswordInput,label='密码')
    
    
from django.contrib.auth.models import User

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')
        
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']
        
from .models import Profile

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')

image_sharing/account/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from .forms import LoginForm, UserRegistrationForm, UserEditForm, ProfileEditForm
from .models import Profile
from django.contrib import messages

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], 
                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})
    
    


@login_required
def dashboard(request):
    return render(request,
                 'account/dashboard.html',
                 {'section': 'dashboard'})

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            profile = Profile.objects.create(user=new_user)
            return render(request,
                        'account/register_done.html',
                        {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request,
                  'account/register.html',
                  {'user_form': user_form})
                  

@login_required
def edit(request):
    try:
        request.user.profile
    except:
        Profile.objects.create(user=request.user)
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, '档案更新成功！')
        else:
            messages.error(request, '档案更新错误！')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
        
    return render(request,
                  'account/edit.html',
                  {'user_form': user_form, 'profile_form': profile_form})
                  

image_sharing/account/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
	<title>{% block title %}{% endblock %}</title>
		<link href="{% static "css/base.css" %}" rel="stylesheet">
	</head>

	<body>
        <div id="header">
            <span class="logo">图片分享</span>
            {% if request.user.is_authenticated %}
                <ul class="menu">
                    <li {% if section == "dashboard" %} class="selected" {% endif %}>
                        <a href="{% url "dashboard" %}">主控面板</a>
                    </li>
                    <li {% if section == "images" %}class="selected"{% endif %}><a href="{% url "images:list" %}">图片</a></li>
                    <li {% if section == "people" %}class="selected"{% endif %}>
                    <a href="#">友人</a>
                    </li>
                </ul>
            {% endif %}
            <span class="user">
                {% if request.user.is_authenticated %}
                    欢迎 {% if request.user.first_name %} {{ request.user.first_name }} {% else %} {{ request.user.username }} {% endif %}, <a href="{% url "logout" %}">注销</a>
                {% else %}
                    <a href="{% url "login" %}">登入</a>
                {% endif %}
            </span>
        </div>
            
        {% if messages %}
            {% for message in messages %}
                <ul class="messages">
                    <li class="{{ message.tags }}">
                        {{ message|safe }}
                        <a id='{{ message.tags }}_{{ forloop.counter }}' href="#" class="close">&times;</a>
                    </li>
                </ul>
            {% endfor %}
        {% endif %}
        
		<div id="content">
		    {% block content %}
		    {% endblock %}
		</div>
		
		<script src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
		
		<script src="http://cdn.bootcss.com/jquery-cookie/1.4.1/jquery.cookie.min.js" ></script>
        <script>
        var csrftoken = $.cookie('csrftoken');
        function csrfSafeMethod(method) {
        // 这些是安全的方法，不需要设置X-CSRFToken
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
        
        $(document).ready(function(){
            {% block domready %}
            {% endblock %}
        });
        </script>
        
        <script>
            $(document).ready(function(e) {
                // delete message
                {% for message in messages %}
                    $('#{{ message.tags }}_{{ forloop.counter }}').click( function(event){
                        $('#{{ message.tags }}_{{ forloop.counter }}' ).parent()[0].setAttribute('style', 'display:none');
                    })
                {% endfor %}
            });
        </script>
        
	</body>
</html>